apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
data:
  CATALOGUE_HOST: "http://catalogue"
  REDIS_HOST: "redis"
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    name: cart
    tier: app
spec:
  containers:
  - name: cart
    image: techworldwithsiva/cart:k8
    imagePullPolicy: Always
    envFrom:
    - configMapRef:
        name: cart-config
    resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    name: cart
    tier: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

