apiVersion: v1
kind: Pod
metadata:
  name: multicontainer  ##Pod name
  namespace: my-namespace
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: almalinux
    image: almalinux
    command: ["sleep","200"]  
