apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod  ##Pod name
  namespace: my-namespace
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
