
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::730335473439:role/eksctl-spot-cluster-nodegroup-spot-NodeInstanceRole-yXHI95MVijHE
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::730335473439:user/eksrbac
      username: eksrbac
kind: ConfigMap
metadata:
  creationTimestamp: "2024-03-25T23:52:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1285"
  uid: eaf6f763-f3df-42e9-abc5-9b9b3ebf23fa
