---
apiVersion: v1
kind: Namespace
metadata:
  name: roboshop
  labels:
    name: roboshop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-admin-role
rules:
- apiGroups: ["*"]
  resources: ["p*ods"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roboshop-admin-rolebinding
  namespace: roboshop
subjects:
- kind: User
  name: eksrbac
  namespace: roboshop
roleRef:
  kind: Role
  name: roboshop-admin-role
  apiGroup: rbac.authorization.k8s.io
---
