apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_DATABASE: "cities"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: c2hpcHBpbmc=  # base64 encoded value of "admin"
  password: c2VjcmV0  # base64 encoded value of "1f2d1e2e67df"
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
    tier: db
spec:
  containers:
  - name: mysql
    image: vkandula650/mysql:k8
    imagePullPolicy: Always
    envFrom:
    - configMapRef:
        name: mysql-config    
    - secretKeyRef:
        name: mysql-secret
          key: username
    resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    name: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3306

