apiVersion: v1
kind: Pod
metadata:
 name: nginx
 namespace: roboshop
spec:
 containers:
 - image: nginx:1.14.2
   imagePullPolicy: Always
   name: nginx 
   ports:
    - containerPort: 80
   resources:
    requests: 
     cpu: "150m"
     memory: "200Mi"
    limits:
     cpu: "200m"
     memory: "300Mi"