apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    tier: db
spec:
  containers:
  - name: mongodb
    image: vkandula650/mongodb:v1
    imagePullPolicy: Always
    resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    name: mongodb
    tier: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

