apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
 REDIS_HOST: "redis"
 MONGO_URL: mongodb://mongodb:27017/catalogue
---
apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    name: user
    tier: app
spec:
  containers:
  - name: user
    image: techworldwithsiva/user:v1
    imagePullPolicy: Always
    envFrom:
    - configMapRef:
        name: user-config
    resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    name: user
    tier: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

